- name: Inspur ESXI Installation
  hosts: inspur
  connection: local
  gather_facts: no
  vars:
    inspur:
      host: "{{ ansible_host}}"
      username: "{{ username }}"
      password: "{{ password }}"
 
  tasks:

  - name: "Ping Inspur"
    shell:
      cmd: "ping -c1 -w 2 {{ansible_host}}"
    register: pingged_host
    ignore_errors: true
    #delegate_to: localhost

  - name: "Result ILO reachability"
    debug:
      msg: "{{ansible_host}} > Ping Sonucu Basarili."
    when: pingged_host.rc == 0
  - local_action: shell date +%Y-%m-%d:%H-%M-%S |tr -d '\n' >>/inspur-ansible/log/kurulum-{{ tstamp.stdout}}.log && echo -e " {{inventory_hostname}} < Inspur Ping Sonucu Basarili. {{ansible_host}}" >> /inspur-ansible/log/kurulum-{{ tstamp.stdout}}.log
    when: pingged_host.rc == 0
    
  - name: "Result ILO reachability"
    debug:
      msg: "{{ansible_host}} > Ping Sonucu Hata Verdi."
    when: pingged_host.rc != 0
  - local_action: shell date +%Y-%m-%d:%H-%M-%S |tr -d '\n' >>/inspur-ansible/log/kurulum-{{ tstamp.stdout}}.log && echo -e " ERROR {{inventory_hostname}} < Inspur Ping Sonucu Basarisiz. {{ansible_host}}" >> /inspur-ansible/log/kurulum-{{ tstamp.stdout}}.log
    when: pingged_host.rc != 0
