- name: Inspur ESXI Installation
  hosts: inspur
  connection: local
  gather_facts: no
  vars:
    inspur:
      host: "{{ ansible_host}}"
      username: "{{ username }}"
      password: "{{ password }}"
 
  tasks:

  - name: "Get power status"
    inspur.ispim.power_status_info:
      provider: "{{ inspur }}"
    register: power_info
